import React from 'react';
import { GameState } from '../types';

interface Props { state: GameState; onNavigate: (tab: 'SANCTUARY' | 'HAREM' | 'CONQUEST' | 'LIBRARY') => void; }

const Dashboard: React.FC<Props> = ({ state, onNavigate }) => {
    const owned = state.roster.filter(c => c.isOwned);
    const active = state.roster.filter(c => (state.settings.activeCharacterIds || ['2']).includes(c.id));
    const conquered = state.nations.reduce((sum, nation) => sum + nation.progress, 0);
    const totalProgress = Math.max(1, state.nations.length * 100);
    const latest = state.logs.slice(-3).reverse();
    const level = Math.max(1, Math.floor(owned.reduce((sum, c) => sum + c.level, 0) / Math.max(1, owned.length)));
    const exp = owned.reduce((sum, c) => sum + (c.exp || 0), 0);
    const expTarget = Math.max(100, level * 100);
    return <div className="absolute inset-0 overflow-y-auto bg-core/50 px-4 py-5 sm:px-6 lg:px-10 lg:py-8"><div className="mx-auto max-w-7xl space-y-6">
        <section className="relative overflow-hidden rounded-2xl border border-primary/25 bg-[linear-gradient(120deg,rgba(35,8,35,.94),rgba(12,5,22,.76))] p-6 shadow-[0_0_35px_rgba(255,0,85,.08)] sm:p-8"><div className="relative z-10 max-w-2xl"><div className="text-[10px] font-black uppercase tracking-[0.35em] text-primary neon-text">SANCTUARY COMMAND</div><h1 className="mt-2 text-3xl font-black tracking-tight text-white sm:text-4xl">圣殿总览</h1><p className="mt-3 max-w-xl text-sm leading-7 text-white/60">圣殿的灯火已经重新点燃。查看在场魔将、推进征服进度，或继续上一段对话。</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => onNavigate('SANCTUARY')} className="rounded-xl bg-primary px-5 py-3 text-xs font-black tracking-widest text-white shadow-[0_0_20px_var(--primary-glow)] transition hover:brightness-110">继续圣殿对话</button><button onClick={() => onNavigate('CONQUEST')} className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-xs font-black tracking-widest text-white/75 transition hover:border-primary/50 hover:text-white">前往征服地图</button></div></div></section>
        <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="玩家等级" value={`LV.${level}`} detail={`${Math.min(100, Math.round((exp % expTarget) / expTarget * 100))}% EXP`} /><Stat label="契约魔将" value={String(owned.length)} detail={`在场 ${active.length} 人`} /><Stat label="征服进度" value={`${Math.round(conquered / totalProgress * 100)}%`} detail={`${state.nations.length} 个区域`} /><Stat label="宝库物资" value={String(state.inventory.length)} detail="件装备" /></section>
        <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="glass-panel rounded-2xl border border-glass p-5 sm:p-6"><div className="flex items-center justify-between border-b border-glass pb-4"><div><div className="text-[10px] font-black uppercase tracking-[0.3em] text-primary">PRESENT IN SANCTUARY</div><h2 className="mt-1 text-xl font-black text-white">当前在场角色</h2></div><button onClick={() => onNavigate('SANCTUARY')} className="text-xs text-dim transition hover:text-primary">管理在场 →</button></div><div className="mt-5 flex flex-wrap gap-3">{active.length ? active.map(c => <div key={c.id} className="flex min-w-[190px] flex-1 items-center gap-3 rounded-xl border border-primary/25 bg-black/20 p-3"><div className="h-12 w-12 shrink-0 overflow-hidden rounded-full border border-primary/50 bg-primary/10">{c.imageUrl ? <img src={c.imageUrl} alt={c.name} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-lg text-primary">✦</div>}</div><div className="min-w-0"><div className="truncate font-bold text-white">{c.name}</div><div className="mt-1 text-[10px] tracking-widest text-primary">{c.title || '契约魔将'} · LV.{c.level}</div></div></div>) : <div className="w-full py-8 text-center text-sm text-dim">暂无在场角色，请前往圣殿选择。</div>}</div></section><section className="glass-panel rounded-2xl border border-glass p-5 sm:p-6"><div className="flex items-center justify-between border-b border-glass pb-4"><div><div className="text-[10px] font-black uppercase tracking-[0.3em] text-primary">RECENT EVENTS</div><h2 className="mt-1 text-xl font-black text-white">最近事件</h2></div><button onClick={() => onNavigate('LIBRARY')} className="text-xs text-dim transition hover:text-primary">查看档案 →</button></div><div className="mt-4 space-y-3">{latest.length ? latest.map(log => <div key={log.id} className="border-l-2 border-primary/60 pl-3"><div className="text-xs text-white/80">{log.content}</div><div className="mt-1 text-[10px] text-dim">{new Date(log.timestamp).toLocaleString('zh-CN')}</div></div>) : <div className="py-8 text-center text-sm text-dim">圣殿还没有新的记录。</div>}</div></section></div>
        <section className="grid gap-3 sm:grid-cols-3"><ActionButton label="召唤魔将" detail="前往召唤阵" onClick={() => onNavigate('HAREM')} /><ActionButton label="管理魔将" detail="查看等级与装备" onClick={() => onNavigate('HAREM')} /><ActionButton label="世界档案" detail="回顾大陆与契约" onClick={() => onNavigate('LIBRARY')} /></section>
    </div></div>;
};
const Stat = ({ label, value, detail }: { label: string; value: string; detail: string }) => <div className="glass-panel rounded-xl border border-glass p-4"><div className="text-[10px] tracking-widest text-dim">{label}</div><div className="mt-2 text-2xl font-black text-white">{value}</div><div className="mt-1 text-[10px] text-primary">{detail}</div></div>;
const ActionButton = ({ label, detail, onClick }: { label: string; detail: string; onClick: () => void }) => <button onClick={onClick} className="glass-panel group rounded-xl border border-glass p-4 text-left transition hover:border-primary/50 hover:bg-primary/5"><div className="font-bold text-white transition group-hover:text-primary">{label} <span className="float-right text-primary">→</span></div><div className="mt-1 text-xs text-dim">{detail}</div></button>;
export default Dashboard;
